name: First Workflow

on: [push]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello world"

  bye-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Bye
        run: echo "Bye world"
