name: Trigger Lab

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'  # Every 2 minutes

jobs:
  handle-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print event type
        run: "echo 'Triggered by: ${{ github.event_name }}'"

  
        
