name: Trigger Lab

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"  # Every 2 minutes

jobs:
  handle-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print event type
        run: |
          echo "Triggered by: ${{ github.event_name }}"

      - name: Check trigger type
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "Code was pushed!"
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manual execution"
          elif [ "${{ github.event_name }}" == "schedule" ]; then
            echo "Running on schedule"
          else
            echo "Unknown trigger: ${{ github.event_name }}"
          fi
